# docker-compose.yml
version: '3'
services:
  scylla:
    image: scylladb/scylla:5.4
    ports:
      - "9042:9042"
    command: --smp 1 --memory 1G

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    ports:
      - "9092:9092"
      - "9644:9644"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --kafka-addr 0.0.0.0:9092
      - --advertise-kafka-addr 127.0.0.1:9092